import type { Metadata } from 'next';
import './globals.css';

import TanstackLayout from '@/components/TanstackLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='light'>
      <TanstackLayout>
        <body className='min-h-dvh'>{children}</body>
      </TanstackLayout>
    </html>
  );
}
